import { Product } from '@/types';

export const INITIAL_PRODUCTS: Product[] = [
  // --- 8 PILIHAN PAKET PRAKTIS (RIVERFORD STYLE - VEG BOXES) ---
  {
    id: 'pkt-01',
    name: 'Paket Hijau Tumis',
    description: 'Cocok untuk 2-3 kali masak. Berisi 1 Ikat Bayam Hijau Premium, 1 Ikat Kangkung Segar, dan 1 Ikat Sawi Hijau/Caisim segar petik subuh.',
    price: 35000,
    category: 'Paket Sayur',
    stock: 50,
    imageUrl: '/images/paket-hijau-tumis-segar.jpg',
    farmerOrigin: '👨‍🌾 Kelompok Tani Organik Lembang, Bandung Barat',
    badgeLabel: '100% Bebas Plastik',
    badgeColor: 'green',
    packageItems: ['1 Ikat Bayam Hijau Premium', '1 Ikat Kangkung Segar', '1 Ikat Sawi Hijau / Caisim'],
    portionInfo: '🍽️ Untuk 2-3 Kali Masak',
    isFeatured: true,
  },
  {
    id: 'pkt-02',
    name: 'Paket Sop Hangat',
    description: 'Lengkap tinggal cemplung. Wortel manis (250g), kentang kuning (250g), buncis segar (150g), serta 1 ikat daun bawang & seledri wangi.',
    price: 45000,
    category: 'Paket Sayur',
    stock: 40,
    imageUrl: '/images/paket-sop-hangat-segar.jpg',
    farmerOrigin: '👨‍🌾 Kebun Sayur Sejahtera Lembang, Bandung',
    badgeLabel: 'Paket Best Seller',
    badgeColor: 'terracotta',
    packageItems: ['Wortel Manis (250g)', 'Kentang Kuning (250g)', 'Buncis Segar (150g)', '1 Ikat Daun Bawang & Seledri'],
    portionInfo: '🍽️ Untuk 4-5 Porsi Hangat',
    isFeatured: true,
  },
  {
    id: 'pkt-03',
    name: 'Paket Bumbu Dapur Dasar',
    description: 'Esensial untuk kebutuhan dapur mingguan. Bawang merah (150g), bawang putih (150g), cabai rawit merah (100g), serta 1 ikat serai & daun salam.',
    price: 40000,
    category: 'Paket Sayur',
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Koperasi Petani Mitra Parongpong, Bandung Barat',
    badgeLabel: 'Esensial Mingguan',
    badgeColor: 'yellow',
    packageItems: ['Bawang Merah (150g)', 'Bawang Putih (150g)', 'Cabai Rawit Merah (100g)', '1 Ikat Serai & Daun Salam'],
    portionInfo: '🍽️ Kebutuhan 1 Minggu',
    isFeatured: true,
  },
  {
    id: 'pkt-04',
    name: 'Paket Sayur Lodeh Gurih',
    description: 'Racikan komplit siap olah kuah santan gurih. Terong ungu segar, labu siam manis, kacang panjang renyah, daun melinjo muda, jagung manis, dan bumbu lodeh aroma rempah.',
    price: 38000,
    category: 'Paket Sayur',
    stock: 45,
    imageUrl: '/images/paket-sayur-lodeh-nusantara.jpg',
    farmerOrigin: '👨‍🌾 Kebun Sayur Tradisional Ciwidey, Bandung Selatan',
    badgeLabel: 'Resep Nusantara',
    badgeColor: 'terracotta',
    packageItems: ['Terong Ungu (200g)', 'Labu Siam Manis (1 Buah)', 'Kacang Panjang (150g)', 'Daun & Buah Melinjo', 'Bumbu Racik Lodeh Alami'],
    portionInfo: '🍽️ Untuk 4 Porsi Gurih',
    isFeatured: true,
  },
  {
    id: 'pkt-05',
    name: 'Paket Sayur Asem Segar Tradisional',
    description: 'Segar dan asam alami khas Sunda. Jagung manis pipil/potong, labu siam muda, kacang panjang renyah, daun & buah melinjo, asem jawa segar, serta kacang tanah.',
    price: 35000,
    category: 'Paket Sayur',
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1518843875459-f738682238a6?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Petani Sayur Lembang, Bandung Barat',
    badgeLabel: 'Menu Favorit Keluarga',
    badgeColor: 'green',
    packageItems: ['Jagung Manis (1 Buah)', 'Labu Siam Muda (1 Buah)', 'Kacang Panjang (150g)', 'Asam Jawa & Melinjo Segar', 'Kacang Tanah & Bumbu'],
    portionInfo: '🍽️ Untuk 4-5 Porsi Segar',
    isFeatured: true,
  },
  {
    id: 'pkt-06',
    name: 'Paket Capcay Komplit Spesial',
    description: 'Pilihan sayuran renyah kaya warna dan nutrisi. Kembang kol padat, brokoli hijau segar, wortel manis lokal, sawi putih, caisim, jamur kuping, serta daun bawang wangi.',
    price: 42000,
    category: 'Paket Sayur',
    stock: 40,
    imageUrl: '/images/paket-capcay.jpg',
    farmerOrigin: '👨‍🌾 Kebun Hortikultura Mitra Lembang & Serpong',
    badgeLabel: 'Kaya Warna & Nutrisi',
    badgeColor: 'sage',
    packageItems: ['Kembang Kol (200g)', 'Wortel Manis (200g)', 'Sawi Putih & Caisim (200g)', 'Jamur Kuping Segar', 'Bumbu Capcay Gurih'],
    portionInfo: '🍽️ Untuk 3-4 Porsi Tumis',
    isFeatured: true,
  },
  {
    id: 'pkt-07',
    name: 'Paket Lalapan & Sambal Dadak',
    description: 'Cocok menemani lauk ayam/ikan goreng. Selada keriting renyah, mentimun lalap segar, kemangi harum wangi, terong bulat hijau, tomat merah, serta cabai rawit pedas nampol.',
    price: 32000,
    category: 'Paket Sayur',
    stock: 35,
    imageUrl: '/images/paket-lalapan-sambal-dadak.jpg',
    farmerOrigin: '👨‍🌾 Kebun Herbal Lembang, Bandung Barat',
    badgeLabel: 'Petik Pagi Harum',
    badgeColor: 'green',
    packageItems: ['Selada Keriting (150g)', 'Kemangi Segar (1 Ikat)', 'Ketimun Lalap (250g)', 'Terong Bulat Hijau (150g)', 'Cabai Rawit & Tomat Sambal'],
    portionInfo: '🍽️ Teman Santap Keluarga',
    isFeatured: true,
  },
  {
    id: 'pkt-08',
    name: 'Paket Salad Sayur Organik (Clean Eating)',
    description: 'Sayuran daun premium siap santap untuk diet sehat dan clean eating. Romaine lettuce renyah, daun selada merah, tomat cherry manis, kyuri mentimun jepang, serta dressing zesty lemon.',
    price: 48000,
    category: 'Paket Sayur',
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Hidroponik Modern Gading Serpong',
    badgeLabel: '100% Organik Bebas Pestisida',
    badgeColor: 'sage',
    packageItems: ['Romaine Lettuce (200g)', 'Tomat Cherry Manis (150g)', 'Kyuri Mentimun Jepang', 'Selada Merah Hidroponik', 'Dressing Zesty Herb'],
    portionInfo: '🍽️ Porsi 2 Piring Sehat',
    isFeatured: true,
  },

  // --- SAYUR SATUAN (A LA CARTE) ---
  {
    id: 'stn-01',
    name: 'Brokoli Kualitas Super (Per Bonggol)',
    description: 'Brokoli hijau padat tanpa ulat dan pestisida sintetis. Pilihan utama untuk MPASI dan masakan sehat keluarga.',
    price: 22000,
    category: 'Sayur Satuan',
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Petani Lembang & Mitra Serpong',
    badgeLabel: 'Superfood',
    badgeColor: 'sage',
  },
  {
    id: 'stn-02',
    name: 'Bayam Hijau Organik (Ikat Besar)',
    description: 'Bayam segar berdaun lebar dipetik subuh, bebas bahan kimia sintetis, kaya zat besi.',
    price: 9000,
    category: 'Sayur Satuan',
    stock: 60,
    imageUrl: '/images/bayam-hijau-segar.jpg',
    farmerOrigin: '👨‍🌾 Kebun Hijau Lembang, Bandung Barat',
    badgeLabel: 'Panen Subuh',
    badgeColor: 'green',
  },
  {
    id: 'stn-03',
    name: 'Kangkung Segar Petik Subuh (Ikat)',
    description: 'Kangkung akar bersih, batang renyah tidak alot saat ditumis, bebas residu pestisida.',
    price: 8000,
    category: 'Sayur Satuan',
    stock: 70,
    imageUrl: '/images/kangkung-segar.jpg',
    farmerOrigin: '👨‍🌾 Kebun Lembang Bandung',
    badgeLabel: 'Paling Segar',
    badgeColor: 'green',
  },
  {
    id: 'stn-04',
    name: 'Sawi Hijau / Caisim (Ikat)',
    description: 'Caisim hijau renyah segar, cocok untuk mie, tumisan, atau campuran sup hangat.',
    price: 8500,
    category: 'Sayur Satuan',
    stock: 55,
    imageUrl: '/images/sawi-hijau-segar.jpg',
    farmerOrigin: '👨‍🌾 Kelompok Tani Curug',
    badgeLabel: 'Organik',
    badgeColor: 'green',
  },
  {
    id: 'stn-05',
    name: 'Sawi Putih Segar (Per Bonggol)',
    description: 'Sawi putih padat dan manis alami, renyah untuk capcay atau sup gurih.',
    price: 14000,
    category: 'Sayur Satuan',
    stock: 45,
    imageUrl: '/images/sawi-putih-segar.jpg',
    farmerOrigin: '👨‍🌾 Petani Mitra Serpong',
    badgeLabel: 'Pilihan Super',
    badgeColor: 'sage',
  },
  {
    id: 'stn-06',
    name: 'Wortel Manis Berastagi (500g)',
    description: 'Wortel warna oranye pekat, renyah manis kaya vitamin A untuk jus atau sayur sup.',
    price: 16000,
    category: 'Sayur Satuan',
    stock: 65,
    imageUrl: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Sayur Gading Serpong',
    badgeLabel: 'Kaya Vitamin A',
    badgeColor: 'terracotta',
  },
  {
    id: 'stn-07',
    name: 'Kentang Dieng Kuning (500g)',
    description: 'Kentang pulen Dieng bebas tanah basah, cocok untuk perkedel, sup, atau kentang goreng.',
    price: 17000,
    category: 'Sayur Satuan',
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Mitra Petani Dieng & Serpong',
    badgeLabel: 'Pulen Alami',
    badgeColor: 'yellow',
  },
  {
    id: 'stn-08',
    name: 'Buncis Renyah Manis (250g)',
    description: 'Buncis muda tanpa serat kasar, renyah manis sangat nikmat untuk tumis bawang putih.',
    price: 11000,
    category: 'Sayur Satuan',
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Hijau Parongpong, Bandung Barat',
    badgeLabel: 'Muda & Renyah',
    badgeColor: 'green',
  },
  {
    id: 'stn-09',
    name: 'Kembang Kol Putih Padat (Per Bonggol)',
    description: 'Kembang kol putih bersih bebas bintik hitam, tekstur renyah dan padat.',
    price: 19000,
    category: 'Sayur Satuan',
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1568584711075-3d021a7c3ca3?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Hortikultura Serpong',
    badgeLabel: 'Kualitas Premium',
    badgeColor: 'sage',
  },
  {
    id: 'stn-10',
    name: 'Terong Ungu Segar (500g)',
    description: 'Terong ungu mulus mengkilap, empuk gurih untuk balado atau sayur lodeh.',
    price: 13000,
    category: 'Sayur Satuan',
    stock: 50,
    imageUrl: '/images/terong-ungu-segar.jpg',
    farmerOrigin: '👨‍🌾 Petani Ciwidey, Bandung Selatan',
    badgeLabel: 'Panen Baru',
    badgeColor: 'green',
  },
  {
    id: 'stn-11',
    name: 'Jagung Manis Madu (2 Buah)',
    description: 'Jagung manis segar berbutir rapat, rasa manis alami untuk sayur asem atau rebus.',
    price: 14000,
    category: 'Sayur Satuan',
    stock: 55,
    imageUrl: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Sayur Cisauk',
    badgeLabel: 'Manis Alami',
    badgeColor: 'yellow',
  },
  {
    id: 'stn-12',
    name: 'Mentimun Lalap Hijau (500g)',
    description: 'Ketimun berair renyah dengan rasa segar, cocok untuk lalapan dan jus dingin.',
    price: 10000,
    category: 'Sayur Satuan',
    stock: 60,
    imageUrl: '/images/mentimun-lalap-segar.jpg',
    farmerOrigin: '👨‍🌾 Kebun Hijau Lembang, Bandung',
    badgeLabel: 'Segar & Berair',
    badgeColor: 'green',
  },
  {
    id: 'stn-13',
    name: 'Labu Siam Muda (2 Buah)',
    description: 'Labu siam hijau mulus tanpa getah pekat, manis untuk sayur lodeh dan sayur bening.',
    price: 12000,
    category: 'Sayur Satuan',
    stock: 45,
    imageUrl: '/images/labu-siam-segar.jpg',
    farmerOrigin: '👨‍🌾 Kebun Sayur Curug',
    badgeLabel: 'Muda Segar',
    badgeColor: 'green',
  },
  {
    id: 'stn-14',
    name: 'Jamur Tiram Putih Segar (250g)',
    description: 'Jamur tiram segar kelopak tebal bersih, kenyal lezat untuk krispi atau tumis.',
    price: 15000,
    category: 'Sayur Satuan',
    stock: 30,
    imageUrl: '/images/jamur-tiram-putih.jpg',
    farmerOrigin: '👨‍🌾 Budidaya Jamur Legok',
    badgeLabel: 'Kenyal Alami',
    badgeColor: 'sage',
  },

  // --- BUAH & BUMBU (A LA CARTE) ---
  {
    id: 'bmb-01',
    name: 'Tomat Merah Segar (500g)',
    description: 'Tomat merah segar pilihan kualitas super dengan rasa manis-asam alami, kaya lycopene dan bebas bahan kimia.',
    price: 18000,
    category: 'Buah & Bumbu',
    stock: 75,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Hijau Lembang, Bandung Barat',
    badgeLabel: 'Panen Subuh',
    badgeColor: 'terracotta',
  },
  {
    id: 'bmb-02',
    name: 'Jeruk Nipis (250g)',
    description: 'Jeruk nipis hijau segar kaya air dan vitamin C alami untuk bumbu penawar amis atau minuman infused water segar.',
    price: 12000,
    category: 'Buah & Bumbu',
    stock: 60,
    imageUrl: '/images/jeruk-nipis.jpg',
    farmerOrigin: '👨‍🌾 Kebun Jeruk Ciwidey, Bandung',
    badgeLabel: 'Kaya Vitamin C',
    badgeColor: 'green',
  },
  {
    id: 'bmb-03',
    name: 'Cabai Rawit Merah Pedas (150g)',
    description: 'Cabai rawit merah segar petik pagi dengan tingkat kepedasan maksimal dan aroma segar alami.',
    price: 18000,
    category: 'Buah & Bumbu',
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Cabai Cisauk',
    badgeLabel: 'Pedas Nampol',
    badgeColor: 'terracotta',
  },
  {
    id: 'bmb-04',
    name: 'Bawang Merah Brebes Pilihan (250g)',
    description: 'Bawang merah Brebes wangi, padat dan beraroma kuat, esensial untuk bumbu masakan harian.',
    price: 19000,
    category: 'Buah & Bumbu',
    stock: 60,
    imageUrl: 'https://images.unsplash.com/photo-1620574387735-3624d75b2dbc?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Petani Bawang Brebes & Pangalengan, Bandung',
    badgeLabel: 'Wangi Khas',
    badgeColor: 'terracotta',
  },
  {
    id: 'bmb-05',
    name: 'Bawang Putih Kating Wangi (250g)',
    description: 'Bawang putih kating siung besar, aroma gurih menyengat sangat sedap untuk tumisan.',
    price: 21000,
    category: 'Buah & Bumbu',
    stock: 55,
    imageUrl: '/images/bawang-putih-kating-segar.jpg',
    farmerOrigin: '👨‍🌾 Mitra Petani Bumbu Serpong',
    badgeLabel: 'Aroma Kuat',
    badgeColor: 'yellow',
  },
  {
    id: 'bmb-06',
    name: 'Alpukat Mentega Super (500g)',
    description: 'Alpukat mentega daging tebal legit tanpa serat pahit, sangat lembut untuk jus dan salad sehat.',
    price: 28000,
    category: 'Buah & Bumbu',
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Buah Serpong',
    badgeLabel: 'Daging Legit',
    badgeColor: 'green',
  },
  {
    id: 'bmb-07',
    name: 'Pisang Sunpride Cavendish (1 Sisir)',
    description: 'Pisang Cavendish kulit kuning mulus, manis harum alami kaya potasium dan energi sehat.',
    price: 26000,
    category: 'Buah & Bumbu',
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Mitra Kebun Buah Banten',
    badgeLabel: 'Manis Alami',
    badgeColor: 'yellow',
  },
  {
    id: 'bmb-08',
    name: 'Pepaya California Manis (1 Buah)',
    description: 'Pepaya California daging merah jingga tebal dan manis segar, sangat baik untuk pencernaan.',
    price: 24000,
    category: 'Buah & Bumbu',
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1517282009859-f000ec3b26fe?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Petani Buah Cisauk',
    badgeLabel: 'Manis Segar',
    badgeColor: 'terracotta',
  },
  {
    id: 'bmb-09',
    name: 'Apel Fuji Manis Segar (500g)',
    description: 'Apel fuji renyah garing dengan rasa manis berair yang menyegarkan dahaga.',
    price: 32000,
    category: 'Buah & Bumbu',
    stock: 45,
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80',
    farmerOrigin: '👨‍🌾 Kebun Buah Mitra Lembang & Serpong',
    badgeLabel: 'Renyah Manis',
    badgeColor: 'terracotta',
  },
];
